In [2]:
import pandas as pd
import numpy as np

In [3]:
deliveries = pd.read_csv('deliveries.csv')

In [4]:
deliveries.head()

,match_id,inning,batting_team,bowling_team,over,ball,batsman,non_striker,bowler,is_super_over,...,bye_runs,legbye_runs,noball_runs,penalty_runs,batsman_runs,extra_runs,total_runs,player_dismissed,dismissal_kind,fielder
0,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,1,1,DA Warner,S Dhawan,TS Mills,0,...,0,0,0,0,0,0,0,NaN,NaN,NaN
1,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,1,2,DA Warner,S Dhawan,TS Mills,0,...,0,0,0,0,0,0,0,NaN,NaN,NaN
2,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,1,3,DA Warner,S Dhawan,TS Mills,0,...,0,0,0,0,4,0,4,NaN,NaN,NaN
3,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,1,4,DA Warner,S Dhawan,TS Mills,0,...,0,0,0,0,0,0,0,NaN,NaN,NaN
4,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,1,5,DA Warner,S Dhawan,TS Mills,0,...,0,0,0,0,0,2,2,NaN,NaN,NaN

QUERY 1 - which bowler has played the minimum no of balls?

In [5]:
count1 = deliveries.groupby('bowler').aggregate('count')
min1 = count1['match_id'].min()
count1

,match_id,inning,batting_team,bowling_team,over,ball,batsman,non_striker,is_super_over,wide_runs,bye_runs,legbye_runs,noball_runs,penalty_runs,batsman_runs,extra_runs,total_runs,player_dismissed,dismissal_kind,fielder
bowler,,,,,,,,,,,,,,,,,,,,
A Ashish Reddy,270,270,270,270,270,270,270,270,270,270,270,270,270,270,270,270,270,19,19,9
A Chandila,234,234,234,234,234,234,234,234,234,234,234,234,234,234,234,234,234,11,11,6
A Choudhary,108,108,108,108,108,108,108,108,108,108,108,108,108,108,108,108,108,5,5,5
A Dananjaya,25,25,25,25,25,25,25,25,25,25,25,25,25,25,25,25,25,0,0,0
A Flintoff,66,66,66,66,66,66,66,66,66,66,66,66,66,66,66,66,66,2,2,1
A Joseph,55,55,55,55,55,55,55,55,55,55,55,55,55,55,55,55,55,6,6,3
A Kumble,983,983,983,983,983,983,983,983,983,983,983,983,983,983,983,983,983,49,49,36
A Mishra,3172,3172,3172,3172,3172,3172,3172,3172,3172,3172,3172,3172,3172,3172,3172,3172,3172,165,165,123
A Mithun,312,312,312,312,312,312,312,312,312,312,312,312,312,312,312,312,312,8,8,6
A Nehra,1974,1974,1974,1974,1974,1974,1974,1974,1974,1974,1974,1974,1974,1974,1974,1974,1974,121,121,91
A Nel,18,18,18,18,18,18,18,18,18,18,18,18,18,18,18,18,18,1,1,1
A Roy,15,15,15,15,15,15,15,15,15,15,15,15,15,15,15,15,15,1,1,1
A Singh,551,551,551,551,551,551,551,551,551,551,551,551,551,551,551,551,551,34,34,26
A Symonds,540,540,540,540,540,540,540,540,540,540,540,540,540,540,540,540,540,23,23,18
A Uniyal,38,38,38,38,38,38,38,38,38,38,38,38,38,38,38,38,38,3,3,2
A Zampa,225,225,225,225,225,225,225,225,225,225,225,225,225,225,225,225,225,19,19,16
AA Chavan,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,8,8,5
AA Jhunjhunwala,88,88,88,88,88,88,88,88,88,88,88,88,88,88,88,88,88,1,1,0
AA Kazi,13,13,13,13,13,13,13,13,13,13,13,13,13,13,13,13,13,1,1,1
AA Noffke,25,25,25,25,25,25,25,25,25,25,25,25,25,25,25,25,25,1,1,1
AB Agarkar,820,820,820,820,820,820,820,820,820,820,820,820,820,820,820,820,820,33,33,27
AB Dinda,1589,1589,1589,1589,1589,1589,1589,1589,1589,1589,1589,1589,1589,1589,1589,1589,1589,82,82,65
AB McDonald,188,188,188,188,188,188,188,188,188,188,188,188,188,188,188,188,188,14,14,8
AC Gilchrist,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1
AC Thomas,327,327,327,327,327,327,327,327,327,327,327,327,327,327,327,327,327,16,16,15
AC Voges,56,56,56,56,56,56,56,56,56,56,56,56,56,56,56,56,56,1,1,1
AD Mascarenhas,310,310,310,310,310,310,310,310,310,310,310,310,310,310,310,310,310,19,19,14
AD Mathews,807,807,807,807,807,807,807,807,807,807,807,807,807,807,807,807,807,28,28,21
AD Russell,1072,1072,1072,1072,1072,1072,1072,1072,1072,1072,1072,1072,1072,1072,1072,1072,1072,60,60,48
AF Milne,115,115,115,115,115,115,115,115,115,115,115,115,115,115,115,115,115,5,5,4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
TL Suman,152,152,152,152,152,152,152,152,152,152,152,152,152,152,152,152,152,7,7,7
TM Dilshan,275,275,275,275,275,275,275,275,275,275,275,275,275,275,275,275,275,5,5,4
TM Head,48,48,48,48,48,48,48,48,48,48,48,48,48,48,48,48,48,3,3,3
TP Sudhindra,74,74,74,74,74,74,74,74,74,74,74,74,74,74,74,74,74,1,1,1
TS Mills,111,111,111,111,111,111,111,111,111,111,111,111,111,111,111,111,111,5,5,2
Tejas Baroka,21,21,21,21,21,21,21,21,21,21,21,21,21,21,21,21,21,0,0,0
UT Yadav,2605,2605,2605,2605,2605,2605,2605,2605,2605,2605,2605,2605,2605,2605,2605,2605,2605,136,136,106
Umar Gul,153,153,153,153,153,153,153,153,153,153,153,153,153,153,153,153,153,14,14,7
V Chakravarthy,18,18,18,18,18,18,18,18,18,18,18,18,18,18,18,18,18,1,1,1
V Kohli,264,264,264,264,264,264,264,264,264,264,264,264,264,264,264,264,264,5,5,4
V Pratap Singh,211,211,211,211,211,211,211,211,211,211,211,211,211,211,211,211,211,12,12,10
V Sehwag,138,138,138,138,138,138,138,138,138,138,138,138,138,138,138,138,138,6,6,4
V Shankar,92,92,92,92,92,92,92,92,92,92,92,92,92,92,92,92,92,2,2,2
VR Aaron,978,978,978,978,978,978,978,978,978,978,978,978,978,978,978,978,978,44,44,37
VRV Singh,371,371,371,371,371,371,371,371,371,371,371,371,371,371,371,371,371,16,16,12
VS Malik,212,212,212,212,212,212,212,212,212,212,212,212,212,212,212,212,212,6,6,5
VS Yeligati,32,32,32,32,32,32,32,32,32,32,32,32,32,32,32,32,32,0,0,0
VY Mahesh,359,359,359,359,359,359,359,359,359,359,359,359,359,359,359,359,359,22,22,17
WA Mota,75,75,75,75,75,75,75,75,75,75,75,75,75,75,75,75,75,4,4,4
WD Parnell,601,601,601,601,601,601,601,601,601,601,601,601,601,601,601,601,601,31,31,24
WPUJC Vaas,288,288,288,288,288,288,288,288,288,288,288,288,288,288,288,288,288,22,22,17
Washington Sundar,358,358,358,358,358,358,358,358,358,358,358,358,358,358,358,358,358,17,17,13
Y Gnaneswara Rao,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,0,0,0
Y Nagar,72,72,72,72,72,72,72,72,72,72,72,72,72,72,72,72,72,4,4,3
Y Venugopal Rao,222,222,222,222,222,222,222,222,222,222,222,222,222,222,222,222,222,7,7,5
YA Abdulla,222,222,222,222,222,222,222,222,222,222,222,222,222,222,222,222,222,15,15,10
YK Pathan,1184,1184,1184,1184,1184,1184,1184,1184,1184,1184,1184,1184,1184,1184,1184,1184,1184,46,46,29
YS Chahal,1841,1841,1841,1841,1841,1841,1841,1841,1841,1841,1841,1841,1841,1841,1841,1841,1841,102,102,76
Yuvraj Singh,882,882,882,882,882,882,882,882,882,882,882,882,882,882,882,882,882,39,39,26
Z Khan,2276,2276,2276,2276,2276,2276,2276,2276,2276,2276,2276,2276,2276,2276,2276,2276,2276,119,119,86

In [6]:
min1

1

In [7]:
bool1 = count1['match_id'] == min1
bool1

bowler
A Ashish Reddy       False
A Chandila           False
A Choudhary          False
A Dananjaya          False
A Flintoff           False
A Joseph             False
A Kumble             False
A Mishra             False
A Mithun             False
A Nehra              False
A Nel                False
A Roy                False
A Singh              False
A Symonds            False
A Uniyal             False
A Zampa              False
AA Chavan            False
AA Jhunjhunwala      False
AA Kazi              False
AA Noffke            False
AB Agarkar           False
AB Dinda             False
AB McDonald          False
AC Gilchrist          True
AC Thomas            False
AC Voges             False
AD Mascarenhas       False
AD Mathews           False
AD Russell           False
AF Milne             False
                     ...
TL Suman             False
TM Dilshan           False
TM Head              False
TP Sudhindra         False
TS Mills             False
Tejas Baroka         False
UT Yadav             False
Umar Gul             False
V Chakravarthy       False
V Kohli              False
V Pratap Singh       False
V Sehwag             False
V Shankar            False
VR Aaron             False
VRV Singh            False
VS Malik             False
VS Yeligati          False
VY Mahesh            False
WA Mota              False
WD Parnell           False
WPUJC Vaas           False
Washington Sundar    False
Y Gnaneswara Rao     False
Y Nagar              False
Y Venugopal Rao      False
YA Abdulla           False
YK Pathan            False
YS Chahal            False
Yuvraj Singh         False
Z Khan               False
Name: match_id, Length: 405, dtype: bool

In [8]:
count1[bool1 == True]

,match_id,inning,batting_team,bowling_team,over,ball,batsman,non_striker,is_super_over,wide_runs,bye_runs,legbye_runs,noball_runs,penalty_runs,batsman_runs,extra_runs,total_runs,player_dismissed,dismissal_kind,fielder
bowler,,,,,,,,,,,,,,,,,,,,
AC Gilchrist,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1

ANSWER 1 - AC GILCHRIST

QUERY 2 - which team has batted maximum no of times in the first inning?

In [9]:
first_inning = deliveries[deliveries['inning'] == 1]
count2 = first_inning.groupby('batting_team').aggregate('count')
max2 = count2['match_id'].max()
count2

,match_id,inning,bowling_team,over,ball,batsman,non_striker,bowler,is_super_over,wide_runs,bye_runs,legbye_runs,noball_runs,penalty_runs,batsman_runs,extra_runs,total_runs,player_dismissed,dismissal_kind,fielder
batting_team,,,,,,,,,,,,,,,,,,,,
Chennai Super Kings,10974,10974,10974,10974,10974,10974,10974,10974,10974,10974,10974,10974,10974,10974,10974,10974,10974,460,460,353
Deccan Chargers,5280,5280,5280,5280,5280,5280,5280,5280,5280,5280,5280,5280,5280,5280,5280,5280,5280,278,278,209
Delhi Capitals,739,739,739,739,739,739,739,739,739,739,739,739,739,739,739,739,739,41,41,31
Delhi Daredevils,8753,8753,8753,8753,8753,8753,8753,8753,8753,8753,8753,8753,8753,8753,8753,8753,8753,442,442,322
Gujarat Lions,1726,1726,1726,1726,1726,1726,1726,1726,1726,1726,1726,1726,1726,1726,1726,1726,1726,100,100,65
Kings XI Punjab,11119,11119,11119,11119,11119,11119,11119,11119,11119,11119,11119,11119,11119,11119,11119,11119,11119,603,603,455
Kochi Tuskers Kerala,876,876,876,876,876,876,876,876,876,876,876,876,876,876,876,876,876,51,51,37
Kolkata Knight Riders,10112,10112,10112,10112,10112,10112,10112,10112,10112,10112,10112,10112,10112,10112,10112,10112,10112,509,509,393
Mumbai Indians,12578,12578,12578,12578,12578,12578,12578,12578,12578,12578,12578,12578,12578,12578,12578,12578,12578,616,616,459
Pune Warriors,2448,2448,2448,2448,2448,2448,2448,2448,2448,2448,2448,2448,2448,2448,2448,2448,2448,125,125,86
Rajasthan Royals,8235,8235,8235,8235,8235,8235,8235,8235,8235,8235,8235,8235,8235,8235,8235,8235,8235,422,422,303
Rising Pune Supergiant,994,994,994,994,994,994,994,994,994,994,994,994,994,994,994,994,994,48,48,29
Rising Pune Supergiants,849,849,849,849,849,849,849,849,849,849,849,849,849,849,849,849,849,37,37,25
Royal Challengers Bangalore,10291,10291,10291,10291,10291,10291,10291,10291,10291,10291,10291,10291,10291,10291,10291,10291,10291,500,500,353
Sunrisers Hyderabad,7768,7768,7768,7768,7768,7768,7768,7768,7768,7768,7768,7768,7768,7768,7768,7768,7768,372,372,284

In [10]:
bool2 = count2['match_id'] == max2

In [11]:
count2[bool2 == True]

,match_id,inning,bowling_team,over,ball,batsman,non_striker,bowler,is_super_over,wide_runs,bye_runs,legbye_runs,noball_runs,penalty_runs,batsman_runs,extra_runs,total_runs,player_dismissed,dismissal_kind,fielder
batting_team,,,,,,,,,,,,,,,,,,,,
Mumbai Indians,12578,12578,12578,12578,12578,12578,12578,12578,12578,12578,12578,12578,12578,12578,12578,12578,12578,616,616,459

ANSWER 2 - MUMBAI INDIANS

QUERY 3 - Which is the most popular toss decision?

In [12]:
matches = pd.read_csv('matches.csv')

In [13]:
matches.head()

,id,season,city,date,team1,team2,toss_winner,toss_decision,result,dl_applied,winner,win_by_runs,win_by_wickets,player_of_match,venue,umpire1,umpire2,umpire3
0,1,2017,Hyderabad,2017-04-05,Sunrisers Hyderabad,Royal Challengers Bangalore,Royal Challengers Bangalore,field,normal,0,Sunrisers Hyderabad,35,0,Yuvraj Singh,"Rajiv Gandhi International Stadium, Uppal",AY Dandekar,NJ Llong,NaN
1,2,2017,Pune,2017-04-06,Mumbai Indians,Rising Pune Supergiant,Rising Pune Supergiant,field,normal,0,Rising Pune Supergiant,0,7,SPD Smith,Maharashtra Cricket Association Stadium,A Nand Kishore,S Ravi,NaN
2,3,2017,Rajkot,2017-04-07,Gujarat Lions,Kolkata Knight Riders,Kolkata Knight Riders,field,normal,0,Kolkata Knight Riders,0,10,CA Lynn,Saurashtra Cricket Association Stadium,Nitin Menon,CK Nandan,NaN
3,4,2017,Indore,2017-04-08,Rising Pune Supergiant,Kings XI Punjab,Kings XI Punjab,field,normal,0,Kings XI Punjab,0,6,GJ Maxwell,Holkar Cricket Stadium,AK Chaudhary,C Shamshuddin,NaN
4,5,2017,Bangalore,2017-04-08,Royal Challengers Bangalore,Delhi Daredevils,Royal Challengers Bangalore,bat,normal,0,Royal Challengers Bangalore,15,0,KM Jadhav,M Chinnaswamy Stadium,NaN,NaN,NaN

In [17]:
toss_groups = matches.groupby('toss_decision').aggregate('count')
toss_groups

,id,season,city,date,team1,team2,toss_winner,result,dl_applied,winner,win_by_runs,win_by_wickets,player_of_match,venue,umpire1,umpire2,umpire3
toss_decision,,,,,,,,,,,,,,,,,
bat,293,293,290,293,293,293,293,293,293,292,293,293,292,293,292,292,20
field,463,463,459,463,463,463,463,463,463,460,463,463,460,463,462,462,99

ANSWER 3 - FIELD

QUERY 4 - In which season were maximum number of games played?

In [20]:
s = matches.groupby('season').aggregate('count')
s

,id,city,date,team1,team2,toss_winner,toss_decision,result,dl_applied,winner,win_by_runs,win_by_wickets,player_of_match,venue,umpire1,umpire2,umpire3
season,,,,,,,,,,,,,,,,,
2008,58,58,58,58,58,58,58,58,58,58,58,58,58,58,58,58,0
2009,57,57,57,57,57,57,57,57,57,57,57,57,57,57,57,57,0
2010,60,60,60,60,60,60,60,60,60,60,60,60,60,60,60,60,0
2011,73,73,73,73,73,73,73,73,73,72,73,73,72,73,73,73,0
2012,74,74,74,74,74,74,74,74,74,74,74,74,74,74,74,74,0
2013,76,76,76,76,76,76,76,76,76,76,76,76,76,76,76,76,0
2014,60,53,60,60,60,60,60,60,60,60,60,60,60,60,60,60,0
2015,59,59,59,59,59,59,59,59,59,57,59,59,57,59,59,59,0
2016,60,60,60,60,60,60,60,60,60,60,60,60,60,60,60,60,0
2017,59,59,59,59,59,59,59,59,59,59,59,59,59,59,58,58,0
2018,60,60,60,60,60,60,60,60,60,60,60,60,60,60,60,60,60
2019,60,60,60,60,60,60,60,60,60,59,60,60,59,60,59,59,59

ANSWER 4 - 2013

QUERY 5 - Which is the most popular venue?

In [22]:
ven_count = matches.groupby('venue').aggregate('count')
ven_count

,id,season,city,date,team1,team2,toss_winner,toss_decision,result,dl_applied,winner,win_by_runs,win_by_wickets,player_of_match,umpire1,umpire2,umpire3
venue,,,,,,,,,,,,,,,,,
ACA-VDCA Stadium,2,2,2,2,2,2,2,2,2,2,2,2,2,2,1,1,1
Barabati Stadium,7,7,7,7,7,7,7,7,7,7,7,7,7,7,7,7,0
Brabourne Stadium,11,11,11,11,11,11,11,11,11,11,11,11,11,11,11,11,0
Buffalo Park,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,0
De Beers Diamond Oval,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,0
Dr DY Patil Sports Academy,17,17,17,17,17,17,17,17,17,17,17,17,17,17,17,17,0
Dr. Y.S. Rajasekhara Reddy ACA-VDCA Cricket Stadium,11,11,11,11,11,11,11,11,11,11,11,11,11,11,11,11,0
Dubai International Cricket Stadium,7,7,0,7,7,7,7,7,7,7,7,7,7,7,7,7,0
Eden Gardens,77,77,77,77,77,77,77,77,77,77,77,77,77,77,77,77,16
Feroz Shah Kotla,67,67,67,67,67,67,67,67,67,67,66,67,67,66,67,67,7
Feroz Shah Kotla Ground,7,7,7,7,7,7,7,7,7,7,7,7,7,7,7,7,7
Green Park,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,0
Himachal Pradesh Cricket Association Stadium,9,9,9,9,9,9,9,9,9,9,9,9,9,9,9,9,0
Holkar Cricket Stadium,9,9,9,9,9,9,9,9,9,9,9,9,9,9,9,9,4
IS Bindra Stadium,7,7,7,7,7,7,7,7,7,7,7,7,7,7,7,7,7
JSCA International Stadium Complex,7,7,7,7,7,7,7,7,7,7,7,7,7,7,7,7,0
Kingsmead,15,15,15,15,15,15,15,15,15,15,15,15,15,15,15,15,0
M Chinnaswamy Stadium,73,73,73,73,73,73,73,73,73,73,71,73,73,71,72,72,7
M. A. Chidambaram Stadium,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8
M. Chinnaswamy Stadium,7,7,7,7,7,7,7,7,7,7,6,7,7,6,7,7,7
"MA Chidambaram Stadium, Chepauk",49,49,49,49,49,49,49,49,49,49,49,49,49,49,49,49,1
Maharashtra Cricket Association Stadium,21,21,21,21,21,21,21,21,21,21,21,21,21,21,21,21,6
Nehru Stadium,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,0
New Wanderers Stadium,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,0
Newlands,7,7,7,7,7,7,7,7,7,7,7,7,7,7,7,7,0
OUTsurance Oval,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,0
"Punjab Cricket Association IS Bindra Stadium, Mohali",14,14,14,14,14,14,14,14,14,14,14,14,14,14,14,14,3
"Punjab Cricket Association Stadium, Mohali",35,35,35,35,35,35,35,35,35,35,35,35,35,35,35,35,0
"Rajiv Gandhi International Stadium, Uppal",56,56,56,56,56,56,56,56,56,56,56,56,56,56,56,56,7
Rajiv Gandhi Intl. Cricket Stadium,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8
"Sardar Patel Stadium, Motera",12,12,12,12,12,12,12,12,12,12,12,12,12,12,12,12,0
Saurashtra Cricket Association Stadium,10,10,10,10,10,10,10,10,10,10,10,10,10,10,10,10,0
Sawai Mansingh Stadium,47,47,47,47,47,47,47,47,47,47,47,47,47,47,47,47,14
Shaheed Veer Narayan Singh International Stadium,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,0
Sharjah Cricket Stadium,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,0
Sheikh Zayed Stadium,7,7,7,7,7,7,7,7,7,7,7,7,7,7,7,7,0
St George's Park,7,7,7,7,7,7,7,7,7,7,7,7,7,7,7,7,0
Subrata Roy Sahara Stadium,17,17,17,17,17,17,17,17,17,17,17,17,17,17,17,17,0
SuperSport Park,12,12,12,12,12,12,12,12,12,12,12,12,12,12,12,12,0
"Vidarbha Cricket Association Stadium, Jamtha",3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,0
Wankhede Stadium,73,73,73,73,73,73,73,73,73,73,73,73,73,73,73,73,16

In [24]:
max = ven_count['id'].max()
max

77

In [25]:
ven_count[ven_count['id'] == max]

,id,season,city,date,team1,team2,toss_winner,toss_decision,result,dl_applied,winner,win_by_runs,win_by_wickets,player_of_match,umpire1,umpire2,umpire3
venue,,,,,,,,,,,,,,,,,
Eden Gardens,77,77,77,77,77,77,77,77,77,77,77,77,77,77,77,77,16

ANSWER 5 - EDEN GARDENS