In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

Which batsmen came to crease but never got a chance to face a ball?

In [5]:
deliveries= pd.read_csv('deliveries.csv')
deliveries.head()

,match_id,inning,batting_team,bowling_team,over,ball,batsman,non_striker,bowler,is_super_over,...,bye_runs,legbye_runs,noball_runs,penalty_runs,batsman_runs,extra_runs,total_runs,player_dismissed,dismissal_kind,fielder
0,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,1,1,DA Warner,S Dhawan,TS Mills,0,...,0,0,0,0,0,0,0,NaN,NaN,NaN
1,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,1,2,DA Warner,S Dhawan,TS Mills,0,...,0,0,0,0,0,0,0,NaN,NaN,NaN
2,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,1,3,DA Warner,S Dhawan,TS Mills,0,...,0,0,0,0,4,0,4,NaN,NaN,NaN
3,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,1,4,DA Warner,S Dhawan,TS Mills,0,...,0,0,0,0,0,0,0,NaN,NaN,NaN
4,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,1,5,DA Warner,S Dhawan,TS Mills,0,...,0,0,0,0,0,2,2,NaN,NaN,NaN

In [14]:
bowlers = deliveries['bowler'].unique()

In [15]:
non_strikers = deliveries['non_striker'].unique()

In [18]:
len(bowlers)

405

In [19]:
len(non_strikers)

511

In [22]:
ans = [x for x in non_strikers if x not in bowlers]

In [24]:
len(ans)

152

ANSWER

In [25]:
ans

['DA Warner',
 'KM Jadhav',
 'JC Buttler',
 'PA Patel',
 'AT Rayudu',
 'MA Agarwal',
 'MS Dhoni',
 'BB McCullum',
 'JJ Roy',
 'KD Karthik',
 'CA Lynn',
 'G Gambhir',
 'M Vohra',
 'HM Amla',
 'WP Saha',
 'DA Miller',
 'Vishnu Vinod',
 'SW Billings',
 'AP Tare',
 'KK Nair',
 'SV Samson',
 'RR Pant',
 'MK Pandey',
 'AB de Villiers',
 'NV Ojha',
 'RV Uthappa',
 'SS Iyer',
 'EJG Morgan',
 'Ishan Kishan',
 'SE Marsh',
 'DM Bravo',
 'AR Bawne',
 'SP Jackson',
 'MJ Guptill',
 'SS Tiwary',
 'IR Jaggi',
 'RT Ponting',
 'W Jaffer',
 'R Dravid',
 'MV Boucher',
 'ML Hayden',
 'MEK Hussey',
 'S Badrinath',
 'KC Sangakkara',
 'SM Katich',
 'T Kohli',
 'M Kaif',
 'DS Lehmann',
 'M Rawat',
 'L Ronchi',
 'PR Shah',
 'S Chanderpaul',
 'VVS Laxman',
 'AS Yadav',
 'DPMD Jayawardene',
 'S Sohal',
 'Kamran Akmal',
 'GC Smith',
 'RR Sarwan',
 'TM Srivastava',
 'DB Das',
 'HH Gibbs',
 'SA Asnodkar',
 'Salman Butt',
 'SP Fleming',
 'Misbah-ul-Haq',
 'YV Takawale',
 'DT Patil',
 'S Anirudha',
 'A Chopra',
 'T Taibu',
 'J Arunkumar',
 'SP Goswami',
 'Niraj Patel',
 'LA Pomersbach',
 'Younis Khan',
 'H Das',
 'R Bishnoi',
 'Yashpal Singh',
 'RJ Quiney',
 'AA Bilakhia',
 'AN Ghosh',
 'MN van Wyk',
 'GJ Bailey',
 'SS Shaikh',
 'Mohammad Ashraful',
 'CA Pujara',
 'OA Shah',
 'Anirudh Singh',
 'P Dogra',
 'MS Bisla',
 'MJ Lumb',
 'DR Martyn',
 'AB Barath',
 'MD Mishra',
 'KB Arun Karthik',
 'RS Sodhi',
 'B Sumanth',
 'C Madan',
 'AG Paunikar',
 'DJ Jacobs',
 'Sunny Singh',
 'UBT Chand',
 'MS Wade',
 'TD Paine',
 'DH Yagnik',
 'BJ Haddin',
 'TR Birt',
 'Harpreet Singh',
 'M Klinger',
 'AC Blizzard',
 'CJ Ferguson',
 'CA Ingram',
 'RE Levi',
 'BB Samantray',
 'AP Majumdar',
 'PA Reddy',
 'MC Juneja',
 'MDKJ Perera',
 'KL Rahul',
 'Q de Kock',
 'CM Gautam',
 'X Thalaivan Sargunam',
 'A Mukund',
 'UA Birla',
 'NJ Maddinson',
 'BR Dunk',
 'RR Rossouw',
 'VH Zol',
 'AD Nath',
 'NS Naik',
 'PSP Handscomb',
 'UT Khawaja',
 'F Behardien',
 'ER Dwivedi',
 'E Lewis',
 'R Singh',
 'S Gill',
 'H Klaasen',
 'P Shaw',
 'A Hales',
 'D Shorey',
 'P Chopra',
 'S Hetmyer',
 'J Bairstow',
 'C Ingram',
 'N Pooran',
 'N Naik',
 'SD Lad',
 'R Bhui',
 'A Turner',
 'S Singh']