In [2]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

2. Which toss decision is best?

In [3]:
matches = pd.read_csv('matches.csv')
deliveries = pd.read_csv('deliveries.csv')

In [4]:
matches.head()

,id,season,city,date,team1,team2,toss_winner,toss_decision,result,dl_applied,winner,win_by_runs,win_by_wickets,player_of_match,venue,umpire1,umpire2,umpire3
0,1,2017,Hyderabad,2017-04-05,Sunrisers Hyderabad,Royal Challengers Bangalore,Royal Challengers Bangalore,field,normal,0,Sunrisers Hyderabad,35,0,Yuvraj Singh,"Rajiv Gandhi International Stadium, Uppal",AY Dandekar,NJ Llong,NaN
1,2,2017,Pune,2017-04-06,Mumbai Indians,Rising Pune Supergiant,Rising Pune Supergiant,field,normal,0,Rising Pune Supergiant,0,7,SPD Smith,Maharashtra Cricket Association Stadium,A Nand Kishore,S Ravi,NaN
2,3,2017,Rajkot,2017-04-07,Gujarat Lions,Kolkata Knight Riders,Kolkata Knight Riders,field,normal,0,Kolkata Knight Riders,0,10,CA Lynn,Saurashtra Cricket Association Stadium,Nitin Menon,CK Nandan,NaN
3,4,2017,Indore,2017-04-08,Rising Pune Supergiant,Kings XI Punjab,Kings XI Punjab,field,normal,0,Kings XI Punjab,0,6,GJ Maxwell,Holkar Cricket Stadium,AK Chaudhary,C Shamshuddin,NaN
4,5,2017,Bangalore,2017-04-08,Royal Challengers Bangalore,Delhi Daredevils,Royal Challengers Bangalore,bat,normal,0,Royal Challengers Bangalore,15,0,KM Jadhav,M Chinnaswamy Stadium,NaN,NaN,NaN

In [7]:
same_winner = matches[matches['toss_winner'] == matches['winner']]
diff_winner = matches[matches['toss_winner'] != matches['winner']]

In [11]:
favourable = same_winner.groupby('toss_decision').aggregate('count')
favourable

,id,season,city,date,team1,team2,toss_winner,result,dl_applied,winner,win_by_runs,win_by_wickets,player_of_match,venue,umpire1,umpire2,umpire3
toss_decision,,,,,,,,,,,,,,,,,
bat,134,134,133,134,134,134,134,134,134,134,134,134,134,134,133,133,10
field,259,259,257,259,259,259,259,259,259,259,259,259,259,259,258,258,57

In [12]:
unfavourable = diff_winner.groupby('toss_decision').aggregate('count')
unfavourable

,id,season,city,date,team1,team2,toss_winner,result,dl_applied,winner,win_by_runs,win_by_wickets,player_of_match,venue,umpire1,umpire2,umpire3
toss_decision,,,,,,,,,,,,,,,,,
bat,159,159,157,159,159,159,159,159,159,158,159,159,158,159,159,159,10
field,204,204,202,204,204,204,204,204,204,201,204,204,201,204,204,204,42

In [13]:
134-159

-25

In [14]:
259-204

55

ANSWER - field as toss_decision is the best